spring:
  datasource:
    username: root
    password: root
    schema: classpath:db.sql
    url: jdbc:mysql://localhost:3306
    initialization-mode: always
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
